#!/bin/bash
set -euo pipefail

RATHENA_HOME=${RATHENA_HOME:-/opt/rathena}
RATHENA_CONF_DIR=${RATHENA_CONF_DIR:-${RATHENA_HOME}/conf}
IMPORT_DIR="${RATHENA_CONF_DIR}/import"
LOG_DIR=${RATHENA_LOG_DIR:-${RATHENA_HOME}/log}

mkdir -p "${IMPORT_DIR}" "${LOG_DIR}"

# Resolve SQL credentials with sensible fallbacks.
LOGIN_DB_HOST=${RATHENA_LOGIN_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}
LOGIN_DB_PORT=${RATHENA_LOGIN_DB_PORT:-${MYSQL_PORT:-3306}}
LOGIN_DB_USER=${RATHENA_LOGIN_DB_USER:-${MYSQL_USER:-ragnarok}}
LOGIN_DB_PASS=${RATHENA_LOGIN_DB_PASSWORD:-${MYSQL_PASSWORD:-ragnarok}}
LOGIN_DB_NAME=${RATHENA_LOGIN_DB_NAME:-${MYSQL_DATABASE:-ragnarok}}

CHAR_DB_HOST=${RATHENA_CHAR_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}
CHAR_DB_PORT=${RATHENA_CHAR_DB_PORT:-${MYSQL_PORT:-3306}}
CHAR_DB_USER=${RATHENA_CHAR_DB_USER:-${MYSQL_USER:-ragnarok}}
CHAR_DB_PASS=${RATHENA_CHAR_DB_PASSWORD:-${MYSQL_PASSWORD:-ragnarok}}
CHAR_DB_NAME=${RATHENA_CHAR_DB_NAME:-${MYSQL_DATABASE:-ragnarok}}

MAP_DB_HOST=${RATHENA_MAP_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}
MAP_DB_PORT=${RATHENA_MAP_DB_PORT:-${MYSQL_PORT:-3306}}
MAP_DB_USER=${RATHENA_MAP_DB_USER:-${MYSQL_USER:-ragnarok}}
MAP_DB_PASS=${RATHENA_MAP_DB_PASSWORD:-${MYSQL_PASSWORD:-ragnarok}}
MAP_DB_NAME=${RATHENA_MAP_DB_NAME:-${MYSQL_DATABASE:-ragnarok}}

LOG_DB_HOST=${RATHENA_LOG_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}
LOG_DB_PORT=${RATHENA_LOG_DB_PORT:-${MYSQL_PORT:-3306}}
LOG_DB_USER=${RATHENA_LOG_DB_USER:-${MYSQL_USER:-ragnarok}}
LOG_DB_PASS=${RATHENA_LOG_DB_PASSWORD:-${MYSQL_PASSWORD:-ragnarok}}
LOG_DB_NAME=${RATHENA_LOG_DB_NAME:-log}

WEB_DB_HOST=${RATHENA_WEB_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}
WEB_DB_PORT=${RATHENA_WEB_DB_PORT:-${MYSQL_PORT:-3306}}
WEB_DB_USER=${RATHENA_WEB_DB_USER:-${MYSQL_USER:-ragnarok}}
WEB_DB_PASS=${RATHENA_WEB_DB_PASSWORD:-${MYSQL_PASSWORD:-ragnarok}}
WEB_DB_NAME=${RATHENA_WEB_DB_NAME:-${MYSQL_DATABASE:-ragnarok}}

SQL_CODEPAGE=${RATHENA_SQL_CODEPAGE:-}

cat > "${IMPORT_DIR}/99-railway-inter.conf" <<EOF
// Generated by docker-entrypoint.sh – do not edit manually.
login_server_ip: ${LOGIN_DB_HOST}
login_server_port: ${LOGIN_DB_PORT}
login_server_id: ${LOGIN_DB_USER}
login_server_pw: ${LOGIN_DB_PASS}
login_server_db: ${LOGIN_DB_NAME}
login_codepage: ${SQL_CODEPAGE}

ipban_db_ip: ${LOGIN_DB_HOST}
ipban_db_port: ${LOGIN_DB_PORT}
ipban_db_id: ${LOGIN_DB_USER}
ipban_db_pw: ${LOGIN_DB_PASS}
ipban_db_db: ${LOGIN_DB_NAME}

char_server_ip: ${CHAR_DB_HOST}
char_server_port: ${CHAR_DB_PORT}
char_server_id: ${CHAR_DB_USER}
char_server_pw: ${CHAR_DB_PASS}
char_server_db: ${CHAR_DB_NAME}

map_server_ip: ${MAP_DB_HOST}
map_server_port: ${MAP_DB_PORT}
map_server_id: ${MAP_DB_USER}
map_server_pw: ${MAP_DB_PASS}
map_server_db: ${MAP_DB_NAME}

web_server_ip: ${WEB_DB_HOST}
web_server_port: ${WEB_DB_PORT}
web_server_id: ${WEB_DB_USER}
web_server_pw: ${WEB_DB_PASS}
web_server_db: ${WEB_DB_NAME}

log_db_ip: ${LOG_DB_HOST}
log_db_port: ${LOG_DB_PORT}
log_db_id: ${LOG_DB_USER}
log_db_pw: ${LOG_DB_PASS}
log_db_db: ${LOG_DB_NAME}
EOF

# Network defaults
LOGIN_BIND_IP=${RATHENA_LOGIN_BIND_IP:-0.0.0.0}
LOGIN_PORT=${RATHENA_LOGIN_PORT:-6900}

CHAR_BIND_IP=${RATHENA_CHAR_BIND_IP:-0.0.0.0}
CHAR_PUBLIC_IP=${RATHENA_CHAR_PUBLIC_IP:-${CHAR_BIND_IP}}
CHAR_PORT=${RATHENA_CHAR_PORT:-6121}
CHAR_LOGIN_IP=${RATHENA_CHAR_LOGIN_IP:-127.0.0.1}
CHAR_LOGIN_PORT=${RATHENA_CHAR_LOGIN_PORT:-6900}

MAP_BIND_IP=${RATHENA_MAP_BIND_IP:-0.0.0.0}
MAP_PUBLIC_IP=${RATHENA_MAP_PUBLIC_IP:-${MAP_BIND_IP}}
MAP_PORT=${RATHENA_MAP_PORT:-5121}
MAP_CHAR_IP=${RATHENA_MAP_CHAR_IP:-127.0.0.1}
MAP_CHAR_PORT=${RATHENA_MAP_CHAR_PORT:-6121}

cat > "${IMPORT_DIR}/99-railway-network.conf" <<EOF
// Generated by docker-entrypoint.sh – do not edit manually.

// login_athena.conf overrides
bind_ip: ${LOGIN_BIND_IP}
login_port: ${LOGIN_PORT}

// char_athena.conf overrides
login_ip: ${CHAR_LOGIN_IP}
login_port: ${CHAR_LOGIN_PORT}
char_ip: ${CHAR_PUBLIC_IP}
char_port: ${CHAR_PORT}
bind_ip: ${CHAR_BIND_IP}

// map_athena.conf overrides
char_ip: ${MAP_CHAR_IP}
char_port: ${MAP_CHAR_PORT}
map_ip: ${MAP_PUBLIC_IP}
map_port: ${MAP_PORT}
bind_ip: ${MAP_BIND_IP}
EOF

# Ensure binaries are on PATH
export PATH="${RATHENA_HOME}:${RATHENA_HOME}/bin:${PATH}"

# Launch servers if no explicit command is provided.
if [[ $# -eq 0 || "$1" == "all" ]]; then
    echo "Starting login-server, char-server, map-server..."
    "${RATHENA_HOME}/login-server" &
    LOGIN_PID=$!
    "${RATHENA_HOME}/char-server" &
    CHAR_PID=$!
    "${RATHENA_HOME}/map-server" &
    MAP_PID=$!

    trap 'kill ${LOGIN_PID} ${CHAR_PID} ${MAP_PID}' TERM INT
    wait -n ${LOGIN_PID} ${CHAR_PID} ${MAP_PID}
else
    exec "$@"
fi
