#!/bin/bash
set -euo pipefail

RATHENA_HOME=${RATHENA_HOME:-/opt/rathena}
RATHENA_CONF_DIR=${RATHENA_CONF_DIR:-${RATHENA_HOME}/conf}
IMPORT_DIR="${RATHENA_CONF_DIR}/import"
LOG_DIR=${RATHENA_LOG_DIR:-${RATHENA_HOME}/log}

mkdir -p "${IMPORT_DIR}" "${LOG_DIR}"

echo "=== Railway Configuration Debug ==="
echo "MYSQL_HOST=${MYSQL_HOST:-not set}"
echo "MYSQL_PORT=${MYSQL_PORT:-not set}"
echo "MYSQL_USER=${MYSQL_USER:-not set}"
echo "MYSQL_PASSWORD=${MYSQL_PASSWORD:-not set (hidden)}"
echo "MYSQL_DATABASE=${MYSQL_DATABASE:-not set}"
echo "===================================="
echo "=== Resolved Variables ==="
echo "LOGIN_DB_HOST will be: ${RATHENA_LOGIN_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}"
echo "LOGIN_DB_PORT will be: ${RATHENA_LOGIN_DB_PORT:-${MYSQL_PORT:-3306}}"
echo "LOGIN_DB_USER will be: ${RATHENA_LOGIN_DB_USER:-${MYSQL_USER:-ragnarok}}"
echo "=========================="

# Resolve SQL credentials with sensible fallbacks.
LOGIN_DB_HOST=${RATHENA_LOGIN_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}
LOGIN_DB_PORT=${RATHENA_LOGIN_DB_PORT:-${MYSQL_PORT:-3306}}
LOGIN_DB_USER=${RATHENA_LOGIN_DB_USER:-${MYSQL_USER:-ragnarok}}
LOGIN_DB_PASS=${RATHENA_LOGIN_DB_PASSWORD:-${MYSQL_PASSWORD:-ragnarok}}
LOGIN_DB_NAME=${RATHENA_LOGIN_DB_NAME:-${MYSQL_DATABASE:-ragnarok}}

CHAR_DB_HOST=${RATHENA_CHAR_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}
CHAR_DB_PORT=${RATHENA_CHAR_DB_PORT:-${MYSQL_PORT:-3306}}
CHAR_DB_USER=${RATHENA_CHAR_DB_USER:-${MYSQL_USER:-ragnarok}}
CHAR_DB_PASS=${RATHENA_CHAR_DB_PASSWORD:-${MYSQL_PASSWORD:-ragnarok}}
CHAR_DB_NAME=${RATHENA_CHAR_DB_NAME:-${MYSQL_DATABASE:-ragnarok}}

MAP_DB_HOST=${RATHENA_MAP_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}
MAP_DB_PORT=${RATHENA_MAP_DB_PORT:-${MYSQL_PORT:-3306}}
MAP_DB_USER=${RATHENA_MAP_DB_USER:-${MYSQL_USER:-ragnarok}}
MAP_DB_PASS=${RATHENA_MAP_DB_PASSWORD:-${MYSQL_PASSWORD:-ragnarok}}
MAP_DB_NAME=${RATHENA_MAP_DB_NAME:-${MYSQL_DATABASE:-ragnarok}}

LOG_DB_HOST=${RATHENA_LOG_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}
LOG_DB_PORT=${RATHENA_LOG_DB_PORT:-${MYSQL_PORT:-3306}}
LOG_DB_USER=${RATHENA_LOG_DB_USER:-${MYSQL_USER:-ragnarok}}
LOG_DB_PASS=${RATHENA_LOG_DB_PASSWORD:-${MYSQL_PASSWORD:-ragnarok}}
LOG_DB_NAME=${RATHENA_LOG_DB_NAME:-${MYSQL_DATABASE:-ragnarok}}

WEB_DB_HOST=${RATHENA_WEB_DB_HOST:-${MYSQL_HOST:-127.0.0.1}}
WEB_DB_PORT=${RATHENA_WEB_DB_PORT:-${MYSQL_PORT:-3306}}
WEB_DB_USER=${RATHENA_WEB_DB_USER:-${MYSQL_USER:-ragnarok}}
WEB_DB_PASS=${RATHENA_WEB_DB_PASSWORD:-${MYSQL_PASSWORD:-ragnarok}}
WEB_DB_NAME=${RATHENA_WEB_DB_NAME:-${MYSQL_DATABASE:-ragnarok}}

SQL_CODEPAGE=${RATHENA_SQL_CODEPAGE:-}

cat > "${IMPORT_DIR}/99-railway-inter.conf" <<EOF
// Generated by docker-entrypoint.sh – do not edit manually.
login_server_ip: ${LOGIN_DB_HOST}
login_server_port: ${LOGIN_DB_PORT}
login_server_id: ${LOGIN_DB_USER}
login_server_pw: ${LOGIN_DB_PASS}
login_server_db: ${LOGIN_DB_NAME}
login_codepage: ${SQL_CODEPAGE}

ipban_db_ip: ${LOGIN_DB_HOST}
ipban_db_port: ${LOGIN_DB_PORT}
ipban_db_id: ${LOGIN_DB_USER}
ipban_db_pw: ${LOGIN_DB_PASS}
ipban_db_db: ${LOGIN_DB_NAME}

char_server_ip: ${CHAR_DB_HOST}
char_server_port: ${CHAR_DB_PORT}
char_server_id: ${CHAR_DB_USER}
char_server_pw: ${CHAR_DB_PASS}
char_server_db: ${CHAR_DB_NAME}

map_server_ip: ${MAP_DB_HOST}
map_server_port: ${MAP_DB_PORT}
map_server_id: ${MAP_DB_USER}
map_server_pw: ${MAP_DB_PASS}
map_server_db: ${MAP_DB_NAME}

web_server_ip: ${WEB_DB_HOST}
web_server_port: ${WEB_DB_PORT}
web_server_id: ${WEB_DB_USER}
web_server_pw: ${WEB_DB_PASS}
web_server_db: ${WEB_DB_NAME}

log_db_ip: ${LOG_DB_HOST}
log_db_port: ${LOG_DB_PORT}
log_db_id: ${LOG_DB_USER}
log_db_pw: ${LOG_DB_PASS}
log_db_db: ${LOG_DB_NAME}
EOF

echo "=== Generated Database Config ==="
echo "Database Host: ${LOGIN_DB_HOST}:${LOGIN_DB_PORT}"
echo "Database User: ${LOGIN_DB_USER}"
echo "Database Name: ${LOGIN_DB_NAME}"
echo "Config file: ${IMPORT_DIR}/99-railway-inter.conf"
cat "${IMPORT_DIR}/99-railway-inter.conf"
echo "=================================="

# Network defaults
LOGIN_BIND_IP=${RATHENA_LOGIN_BIND_IP:-0.0.0.0}
LOGIN_PORT=${RATHENA_LOGIN_PORT:-6900}

# Try to auto-detect Railway public domain
RAILWAY_PUBLIC=${RAILWAY_PUBLIC_DOMAIN:-${RAILWAY_STATIC_URL:-}}

# Login server needs to know where to redirect clients (char/map public addresses)
LOGIN_CHAR_SERVER_IP=${RATHENA_CHAR_SERVER_IP:-66.33.22.230}
LOGIN_CHAR_SERVER_PORT=${RATHENA_CHAR_SERVER_PORT:-55237}
LOGIN_MAP_SERVER_IP=${RATHENA_MAP_SERVER_IP:-66.33.22.248}
LOGIN_MAP_SERVER_PORT=${RATHENA_MAP_SERVER_PORT:-12246}

CHAR_BIND_IP=${RATHENA_CHAR_BIND_IP:-0.0.0.0}
CHAR_PUBLIC_IP=${RATHENA_CHAR_PUBLIC_IP:-66.33.22.230}
# Use same port for internal listening and external advertising (Railway TCP proxy forwards 55237->55237)
CHAR_LISTEN_PORT=${RATHENA_CHAR_LISTEN_PORT:-55237}
CHAR_PUBLIC_PORT=${RATHENA_CHAR_PUBLIC_PORT:-55237}
CHAR_LOGIN_IP=${RATHENA_CHAR_LOGIN_IP:-warnarok-copy.railway.internal}
CHAR_LOGIN_PORT=${RATHENA_CHAR_LOGIN_PORT:-6900}

MAP_BIND_IP=${RATHENA_MAP_BIND_IP:-0.0.0.0}
MAP_PUBLIC_IP=${RATHENA_MAP_PUBLIC_IP:-66.33.22.248}
# Use same port for internal listening and external advertising (Railway TCP proxy forwards 12246->12246)
MAP_LISTEN_PORT=${RATHENA_MAP_LISTEN_PORT:-12246}
MAP_PUBLIC_PORT=${RATHENA_MAP_PUBLIC_PORT:-12246}
MAP_CHAR_IP=${RATHENA_MAP_CHAR_IP:-warnarok-castri-6121.railway.internal}
MAP_CHAR_PORT=${RATHENA_MAP_CHAR_PORT:-55237}

# Generate server-specific config files to avoid duplicate keys
# Login server config
echo "DEBUG: LOGIN_CHAR_SERVER_IP=${LOGIN_CHAR_SERVER_IP}"
echo "DEBUG: LOGIN_CHAR_SERVER_PORT=${LOGIN_CHAR_SERVER_PORT}"
cat > "${IMPORT_DIR}/99-railway-network-login.conf" <<EOF
// Generated by docker-entrypoint.sh – do not edit manually.
// Login server configuration
bind_ip: ${LOGIN_BIND_IP}
login_port: ${LOGIN_PORT}
// Char server address advertised to clients after login
char_server_ip: ${LOGIN_CHAR_SERVER_IP}
char_server_port: ${LOGIN_CHAR_SERVER_PORT}
// Enable debug logging
console_msg_log: 7
EOF

# Char server config
# char_ip: Public hostname/IP advertised to clients
# char_port: BOTH the listening port AND the advertised port
# Since Railway TCP proxy forwards external:55237 -> internal:6121,
# we need to advertise the EXTERNAL port (55237) while listening on INTERNAL port (6121)
# BUT rAthena uses char_port for both! So we must choose:
# Option: Listen on external port and configure TCP proxy to match (external -> external)
cat > "${IMPORT_DIR}/99-railway-network-char.conf" <<EOF
// Generated by docker-entrypoint.sh – do not edit manually.
// Char server configuration
login_ip: ${CHAR_LOGIN_IP}
login_port: ${CHAR_LOGIN_PORT}
char_ip: ${CHAR_PUBLIC_IP}
char_port: ${CHAR_PUBLIC_PORT}
bind_ip: ${CHAR_BIND_IP}
// Enable debug logging to see client connection details
console_msg_log: 7
EOF

# Map server config
# map_port: BOTH the listening port AND the advertised port
# Same issue as char server - we use PUBLIC_PORT so clients can connect via TCP proxy
cat > "${IMPORT_DIR}/99-railway-network-map.conf" <<EOF
// Generated by docker-entrypoint.sh – do not edit manually.
// Map server configuration
char_ip: ${MAP_CHAR_IP}
char_port: ${MAP_CHAR_PORT}
map_ip: ${MAP_PUBLIC_IP}
map_port: ${MAP_PUBLIC_PORT}
bind_ip: ${MAP_BIND_IP}
EOF

# For backward compatibility, create a combined file (will be used if specific files aren't imported)
cat > "${IMPORT_DIR}/99-railway-network.conf" <<EOF
// Generated by docker-entrypoint.sh – do not edit manually.
// DEPRECATED: Use server-specific files instead to avoid duplicate keys
// This file is kept for backward compatibility only

// login_athena.conf overrides
bind_ip: ${LOGIN_BIND_IP}
login_port: ${LOGIN_PORT}

// char_athena.conf overrides
login_ip: ${CHAR_LOGIN_IP}
login_port: ${CHAR_LOGIN_PORT}
char_ip: ${CHAR_PUBLIC_IP}
char_port: ${CHAR_PUBLIC_PORT}
bind_ip: ${CHAR_BIND_IP}
port: ${CHAR_LISTEN_PORT}

// map_athena.conf overrides
char_ip: ${MAP_CHAR_IP}
char_port: ${MAP_CHAR_PORT}
map_ip: ${MAP_PUBLIC_IP}
map_port: ${MAP_PUBLIC_PORT}
bind_ip: ${MAP_BIND_IP}
port: ${MAP_LISTEN_PORT}
EOF

echo "=== Generated Network Config Files ==="
echo "Login server config:"
cat "${IMPORT_DIR}/99-railway-network-login.conf"
echo ""
echo "Char server config:"
cat "${IMPORT_DIR}/99-railway-network-char.conf"
echo ""
echo "Map server config:"
cat "${IMPORT_DIR}/99-railway-network-map.conf"
echo "======================================="

# Ensure binaries are on PATH
export PATH="${RATHENA_HOME}:${RATHENA_HOME}/bin:${PATH}"

# Determine which servers to start based on START_SERVERS environment variable
# Defaults to "all" if not set
START_SERVERS=${START_SERVERS:-all}

echo "=== Server Startup Configuration ==="
echo "START_SERVERS=${START_SERVERS}"
echo "===================================="

# Launch servers if no explicit command is provided.
if [[ $# -eq 0 ]]; then
    PIDS=()
    
    if [[ "$START_SERVERS" == "all" || "$START_SERVERS" == *"login"* ]]; then
        echo "Starting login-server..."
        "${RATHENA_HOME}/login-server" &
        LOGIN_PID=$!
        PIDS+=($LOGIN_PID)
        echo "Login server started with PID: $LOGIN_PID"
    fi
    
    if [[ "$START_SERVERS" == "all" || "$START_SERVERS" == *"char"* ]]; then
        echo "Starting char-server..."
        "${RATHENA_HOME}/char-server" &
        CHAR_PID=$!
        PIDS+=($CHAR_PID)
        echo "Char server started with PID: $CHAR_PID"
    fi
    
    if [[ "$START_SERVERS" == "all" || "$START_SERVERS" == *"map"* ]]; then
        echo "Starting map-server..."
        "${RATHENA_HOME}/map-server" &
        MAP_PID=$!
        PIDS+=($MAP_PID)
        echo "Map server started with PID: $MAP_PID"
    fi
    
    if [[ ${#PIDS[@]} -eq 0 ]]; then
        echo "Error: No servers configured to start. Set START_SERVERS environment variable."
        echo "Valid values: all, login, char, map (or comma-separated combinations)"
        exit 1
    fi
    
    echo "All configured servers started. PIDs: ${PIDS[@]}"
    trap "kill ${PIDS[@]} 2>/dev/null" TERM INT
    wait -n ${PIDS[@]}
else
    exec "$@"
fi
